# Generated by Django 4.1.4 on 2023-01-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_blog_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
